# Generated by Django 2.2.2 on 2019-07-18 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=255)),
                ('product_img', models.CharField(default='', max_length=255)),
                ('processor', models.CharField(max_length=255)),
                ('ram', models.CharField(default=0, max_length=50)),
                ('storage', models.CharField(max_length=255)),
                ('display_size', models.CharField(max_length=255)),
                ('resolution', models.CharField(max_length=255)),
                ('description', models.TextField(default='')),
                ('price', models.CharField(default='0', max_length=255)),
                ('number_in_stock', models.IntegerField(default=0)),
                ('category', models.CharField(default='', max_length=100)),
                ('ports', models.CharField(default='', max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=255)),
                ('product_img', models.CharField(default='', max_length=255)),
                ('processor', models.CharField(max_length=255)),
                ('ram', models.CharField(default=0, max_length=50)),
                ('storage', models.CharField(max_length=255)),
                ('display_size', models.CharField(max_length=255)),
                ('resolution', models.CharField(max_length=255)),
                ('description', models.TextField(default='')),
                ('price', models.CharField(default='0', max_length=255)),
                ('number_in_stock', models.IntegerField(default=0)),
                ('battery', models.CharField(max_length=255)),
                ('camera', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
