# Generated by Django 2.2.2 on 2019-07-18 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='laptop',
            old_name='display_size',
            new_name='display',
        ),
        migrations.RenameField(
            model_name='phone',
            old_name='display_size',
            new_name='display',
        ),
        migrations.RemoveField(
            model_name='laptop',
            name='resolution',
        ),
        migrations.RemoveField(
            model_name='phone',
            name='resolution',
        ),
        migrations.AddField(
            model_name='laptop',
            name='GPU',
            field=models.CharField(default='', max_length=100),
        ),
    ]
