# Generated by Django 2.2.2 on 2019-07-22 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20190718_2326'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptop',
            name='model_id',
            field=models.CharField(default='170', max_length=5),
        ),
        migrations.AddField(
            model_name='phone',
            name='model_id',
            field=models.CharField(default='170', max_length=5),
        ),
    ]
