# Generated by Django 2.2.2 on 2019-08-03 16:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20190722_1657'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='laptop',
            options={'get_latest_by': ('time_added',), 'ordering': ('time_added',)},
        ),
        migrations.AlterModelOptions(
            name='phone',
            options={'get_latest_by': ('time_added',), 'ordering': ('time_added',)},
        ),
        migrations.AddField(
            model_name='laptop',
            name='time_added',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='phone',
            name='time_added',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name=django.utils.timezone.now),
        ),
    ]
