# Generated by Django 2.2.2 on 2019-08-03 16:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20190803_2140'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='laptop',
            options={'get_latest_by': ('date_added',), 'ordering': ('date_added',)},
        ),
        migrations.AlterModelOptions(
            name='phone',
            options={'get_latest_by': ('date_added',), 'ordering': ('date_added',)},
        ),
        migrations.RemoveField(
            model_name='laptop',
            name='time_added',
        ),
        migrations.RemoveField(
            model_name='phone',
            name='time_added',
        ),
        migrations.AddField(
            model_name='laptop',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='phone',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
